angular.module('libraryManagement', ['ngStorage',
    'ngRoute',
    'addBook',
    'updateBook',
    'listBooks',
    'signUp',
    'logIn',
    'allBooks',
    'viewBooks',
    'issuedBooks',
    'requestedBooks',
    'adminLanding',
    'pendingRequest', 'adminIssuedbooks', 'userLanding']);
